name: Деплой
on:
  pull_request:
    types:
      - synchronized
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: composeApp
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Тащим ключик
        run: |
          echo "${{ secrets.SSH_KEY }}" > deploy_key.pem
          chmod 600 deploy_key.pem
          
      - name: Копируем билд на сервер
        run: |
          rsync -avz --delete -e "ssh -p ${{ secrets.SSH_PORT }}" \
            build/dist/wasmJs/productionExecutable/ \
            ${{ secrets.USER }}@${{ secrets.HOST }}:/srv/schedule/web/dist/